services:
  static-web:
    image: nginx:alpine
    container_name: <container-name>
    environments:
      - WEB_HOST=${WEB_HOST}
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-web.rule=Host(`${WEB_HOST}`)"
      - "traefik.http.routers.static-web.entrypoints=websecure"
      - "traefik.http.services.static-web.loadbalancer.server.port=80"
      - "traefik.http.routers.static-web.tls=true"
      - "traefik.http.routers.static-web.tls.certresolver=letsencrypt"
    networks:
      - shared-network
    restart: unless-stopped

networks:
  shared-network:
    external: true
